def map_listing_for_frontend(l):
    """
    Map a raw listing dict (from extract_simple_listings_from_html) to the full set of frontend-compatible fields.
    """
    return {
        'address.street_name': l.get('address') or l.get('address.street_name'),
        'address.house_number': l.get('address.house_number'),
        'address.postal_code': l.get('area_code') or l.get('address.postal_code'),
        'address.city': l.get('city') or l.get('address.city'),
        'price.rent_price': l.get('price') or l.get('price.rent_price'),
        'price.rent_price_type': l.get('price.rent_price_type', 'per maand'),
        'floor_area': l.get('area') or l.get('floor_area'),
        'plot_area': l.get('plot_area'),
        'number_of_rooms': l.get('bedrooms') or l.get('number_of_rooms'),
        'number_of_bedrooms': l.get('bedrooms') or l.get('number_of_bedrooms'),
        'number_of_bathrooms': l.get('bathrooms') or l.get('number_of_bathrooms'),
        'energy_label': l.get('energy_label'),
        'object_type': l.get('object_type'),
        'type': l.get('type'),
        'status': l.get('status'),
        'agent.name': l.get('agent.name'),
        'publish_date': l.get('publish_date'),
        'object_detail_page_relative_url': l.get('funda_url') or l.get('object_detail_page_relative_url'),
        'image_url': l.get('image_url'),
        'listed_since': l.get('listed_since'),
        'listed_days_ago': l.get('listed_days_ago'),
        'furnished': l.get('furnished'),
        'partly_furnished': l.get('partly_furnished'),
        'service_costs_included': l.get('service_costs_included'),
        'service_costs_excluded': l.get('service_costs_excluded'),
        'construction_type': l.get('construction_type'),
        'build_period': l.get('build_period'),
        'balcony': l.get('balcony'),
        'roof_terrace': l.get('roof_terrace'),
        'garden': l.get('garden'),
        'lift': l.get('lift'),
        'single_floor': l.get('single_floor'),
        'disabled_access': l.get('disabled_access'),
        'elderly_access': l.get('elderly_access'),
        'description': l.get('description', ''),
    }
